// Same-origin, read-only Overpass relay. Accepts the exact query generated by
// Plot Scout in JSON or form encoding.
//
// Reliability model: mirrors are "hedged" — the primary starts immediately, the
// next mirror starts if the previous one has not answered after a short stagger,
// and the first VALID response wins (the rest are aborted). This keeps load on
// public infrastructure low while a slow/dead mirror cannot stall the request.
const UPSTREAMS = [
  "https://overpass.private.coffee/api/interpreter",
  "https://overpass-api.de/api/interpreter",
  "https://maps.mail.ru/osm/tools/overpass/api/interpreter"
];
const MAX_QUERY_CHARS = 4000;
const UPSTREAM_TIMEOUT_MS = 9000; // per mirror, from its own start
const STAGGER_MS = 2500;          // delay before starting the next mirror
const PROXY_DEADLINE_MS = 10000;  // hard cap; client aborts at ~12s

async function getQuery(req) {
  if (typeof req.body?.query === "string") return req.body.query;
  if (typeof req.body === "string") {
    const params = new URLSearchParams(req.body);
    return params.get("data") || "";
  }
  if (req.body && typeof req.body === "object" && typeof req.body.data === "string") return req.body.data;
  return "";
}

async function fetchOne(upstream, query, stopSignal) {
  const controller = new AbortController();
  const onStop = () => controller.abort();
  stopSignal.addEventListener("abort", onStop, { once: true });
  const timer = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS);
  try {
    const r = await fetch(upstream, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        Accept: "application/json",
        "User-Agent": "PlotScout/1.3 (map-intelligence relay)"
      },
      body: `data=${encodeURIComponent(query)}`,
      signal: controller.signal
    });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const data = await r.json();
    if (!data || !Array.isArray(data.elements)) throw new Error("invalid-overpass-response");
    if (typeof data.remark === "string" && /runtime error|out of memory|timed out/i.test(data.remark)) throw new Error("incomplete-overpass-response");
    return data;
  } finally {
    clearTimeout(timer);
    stopSignal.removeEventListener("abort", onStop);
  }
}

// Resolves with the first valid response; rejects when every mirror failed or the deadline passed.
function hedgedQuery(query) {
  return new Promise((resolve, reject) => {
    const stop = new AbortController(); // aborts every in-flight / pending mirror
    let settled = false;
    let failures = 0;
    const end = (fn, value) => {
      if (settled) return;
      settled = true;
      clearTimeout(deadline);
      stop.abort();
      fn(value);
    };
    const deadline = setTimeout(() => end(reject, new Error("deadline")), PROXY_DEADLINE_MS);
    const started = new Set();
    const start = (index) => {
      if (settled || index >= UPSTREAMS.length || started.has(index)) return;
      started.add(index);
      // Next mirror starts after the stagger, or immediately if this one fails.
      const next = setTimeout(() => start(index + 1), STAGGER_MS);
      stop.signal.addEventListener("abort", () => clearTimeout(next), { once: true });
      fetchOne(UPSTREAMS[index], query, stop.signal).then(
        (data) => end(resolve, data),
        () => {
          failures += 1;
          clearTimeout(next);
          if (failures === UPSTREAMS.length) end(reject, new Error("all-mirrors-failed"));
          else start(index + 1);
        }
      );
    };
    start(0);
  });
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });
  const query = await getQuery(req);
  if (!query || query.length > MAX_QUERY_CHARS || !query.startsWith("[out:json]") || /\b(out\s+meta|foreach|convert)\b/.test(query)) return res.status(400).json({ error: "Invalid query" });

  try {
    const data = await hedgedQuery(query);
    res.setHeader("Cache-Control", "no-store");
    return res.status(200).json(data);
  } catch {
    return res.status(502).json({ error: "Map service unreachable" });
  }
}
